-- ==============================================================================
-- SCHEMA MEATMASTER PRO - NHOST (POSTGRESQL + HASURA)
-- ==============================================================================

-- 1. TENANTS (EMPRESAS/LOJAS)
create table public.tenants (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  owner_name text,
  email text,
  plan text default 'Start', -- 'Start', 'Profissional', 'Enterprise'
  status text default 'active', -- 'active', 'suspended', 'expired'
  expires_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. PROFILES (USUÁRIOS DO SISTEMA)
-- Vincula com auth.users do Nhost
create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  tenant_id bigint references public.tenants(id) on delete cascade,
  username text,
  name text,
  role text default 'cashier', -- 'admin', 'cashier', 'stock_manager'
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. PRODUCTS (PRODUTOS)
create table public.products (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade not null,
  name text not null,
  description text,
  price numeric(10,2) not null default 0,
  promotional_price numeric(10,2),
  cost_price numeric(10,2),
  unit text default 'un', -- 'kg', 'un'
  category_name text,
  image_url text,
  is_kit boolean default false,
  stock_quantity numeric(10,3) default 0,
  min_stock_level numeric(10,3) default 5,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. CUSTOMERS (CLIENTES)
create table public.customers (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade not null,
  name text not null,
  phone text,
  email text,
  address text,
  city text,
  state text,
  zip_code text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 5. SUPPLIERS (FORNECEDORES)
create table public.suppliers (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade not null,
  name text not null,
  contact_person text,
  phone text,
  email text,
  address text,
  cnpj text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 6. ORDERS (PEDIDOS/VENDAS)
create table public.orders (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade not null,
  customer_id bigint references public.customers(id) on delete set null,
  total_amount numeric(10,2) not null default 0,
  subtotal numeric(10,2) not null default 0,
  delivery_fee numeric(10,2) default 0,
  discount numeric(10,2) default 0,
  status text default 'pending', -- 'pending', 'completed', 'cancelled', 'delivery'
  payment_method text, -- 'credit', 'debit', 'cash', 'pix'
  delivery_type text default 'pickup', -- 'pickup', 'delivery'
  delivery_address text,
  notes text,
  created_by uuid references public.profiles(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 7. ORDER ITEMS (ITENS DO PEDIDO)
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete set null,
  quantity numeric(10,3) not null,
  unit_price numeric(10,2) not null,
  total_price numeric(10,2) not null,
  created_at timestamptz default now()
);

-- 8. TRANSACTIONS (FINANCEIRO)
create table public.transactions (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade not null,
  type text not null, -- 'income', 'expense'
  amount numeric(10,2) not null,
  description text,
  category text,
  payment_method text,
  date date default current_date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 9. SETTINGS (CONFIGURAÇÕES DA LOJA)
create table public.settings (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id) on delete cascade not null unique,
  address text,
  phone text,
  whatsapp text,
  instagram text,
  facebook text,
  opening_hours text,
  logo_url text,
  cnpj text,
  delivery_fee numeric(10,2) default 0,
  primary_color text default '#DC2626',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) & POLICIES (NATIVE POSTGRES FOR HASURA)
-- ==============================================================================

-- Habilitar RLS em todas as tabelas sensíveis
alter table public.tenants enable row level security;
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.suppliers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.transactions enable row level security;
alter table public.settings enable row level security;

-- Função Helper para pegar o ID do usuário atual (Nhost/Hasura)
create or replace function get_current_user_id()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;

-- Função Helper para pegar o tenant_id do usuário atual
create or replace function get_auth_tenant_id()
returns bigint
language sql
security definer
stable
as $$
  select tenant_id from public.profiles where id = get_current_user_id();
$$;

-- Função Helper para verificar se é Service Role (Admin Global do Hasura)
-- O Hasura envia 'x-hasura-role' = 'admin' quando usamos a admin secret
create or replace function is_admin()
returns boolean
language sql
stable
as $$
  select current_setting('request.jwt.claim.role', true) = 'service_role' 
      or current_setting('hasura.role', true) = 'admin';
$$;

-- 1. TENANTS POLICIES
create policy "Users can view own tenant" on public.tenants
  for select using (
    id = get_auth_tenant_id() 
    or is_admin()
  );

-- 2. PROFILES POLICIES
create policy "Users can view profiles in same tenant" on public.profiles
  for select using (
    tenant_id = get_auth_tenant_id()
    or id = get_current_user_id()
    or is_admin()
  );

create policy "Users can update own profile" on public.profiles
  for update using (id = get_current_user_id());

-- 3. PRODUCTS POLICIES
create policy "View products same tenant" on public.products
  for select using (
    tenant_id = get_auth_tenant_id()
    or is_admin()
  );

create policy "Manage products same tenant" on public.products
  for all using (
    tenant_id = get_auth_tenant_id()
    or is_admin()
  );

-- Public access for Online Store (Leitura pública)
-- No Nhost/Hasura, usuários anônimos têm role 'public' ou 'anonymous'
-- Assumindo que a role anônima não tem tenant_id, permitimos select irrestrito
-- ou filtrado via API. Para RLS nativo, permitimos tudo no SELECT se for público.
create policy "Public view products" on public.products
  for select using (true);

-- 4. CUSTOMERS POLICIES
create policy "Manage customers same tenant" on public.customers
  for all using (
    tenant_id = get_auth_tenant_id()
    or is_admin()
  );

-- 5. SUPPLIERS POLICIES
create policy "Manage suppliers same tenant" on public.suppliers
  for all using (
    tenant_id = get_auth_tenant_id()
    or is_admin()
  );

-- 6. ORDERS POLICIES
create policy "Manage orders same tenant" on public.orders
  for all using (
    tenant_id = get_auth_tenant_id()
    or is_admin()
  );

create policy "Public create orders" on public.orders
  for insert with check (true);

-- 7. ORDER ITEMS POLICIES
create policy "Manage order items same tenant" on public.order_items
  for all using (
    exists (
      select 1 from public.orders
      where public.orders.id = public.order_items.order_id
      and (public.orders.tenant_id = get_auth_tenant_id() or is_admin())
    )
  );

create policy "Public create order items" on public.order_items
  for insert with check (true);

-- 8. TRANSACTIONS POLICIES
create policy "Manage transactions same tenant" on public.transactions
  for all using (
    tenant_id = get_auth_tenant_id()
    or is_admin()
  );

-- 9. SETTINGS POLICIES
create policy "View settings same tenant" on public.settings
  for select using (
    tenant_id = get_auth_tenant_id()
    or is_admin()
  );

create policy "Update settings same tenant" on public.settings
  for update using (
    tenant_id = get_auth_tenant_id()
    or is_admin()
  );

create policy "Public view settings" on public.settings
  for select using (true);

-- ==============================================================================
-- TRIGGERS & FUNCTIONS
-- ==============================================================================

-- Trigger para criar perfil automaticamente ao criar usuário no Auth (Nhost)
-- A tabela de usuários no Nhost é auth.users
create or replace function public.handle_new_nhost_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, tenant_id, username, name, role)
  values (
    new.id,
    (new.metadata->>'tenant_id')::bigint,
    new.metadata->>'username',
    new.display_name,
    coalesce(new.metadata->>'role', 'cashier')
  );
  return new;
end;
$$;

-- Nota: No Nhost, você deve garantir que tem permissão para criar triggers no schema auth.
-- Caso contrário, use Hasura Event Triggers.
-- Tentativa de criar trigger nativo (geralmente funciona se for superuser do DB):
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_nhost_user();

-- Indexes para performance
create index idx_products_tenant on public.products(tenant_id);
create index idx_orders_tenant on public.orders(tenant_id);
create index idx_customers_tenant on public.customers(tenant_id);
create index idx_profiles_tenant on public.profiles(tenant_id);
